USE [NetACS]
GO

/****** Object:  Table [dbo].[Device]    Script Date: 15/11/2019 08:52:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Device](
	[ID] [uniqueidentifier] ROWGUIDCOL  NOT NULL,
	[DeviceName] [varchar](50) NULL,
 CONSTRAINT [PK_Device] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

ALTER TABLE [dbo].[Device] ADD  CONSTRAINT [DF_Device_ID]  DEFAULT (newid()) FOR [ID]
GO